### PR TITLE
Added a progressbar component

### PR DESCRIPTION
**Pull request by markusamuel**

### CODE REVIEW

**Comment by mark-yacoub** [comment]
Fixed the conflict and pushed a fixed one.
Do not do a pull. instead, delete your local branch, pull master and pull the new update branch from origin.

**Comment by mark-yacoub** [comment]
there is warning here that's very easy to fix. make sure your code never introduces errors or warnings:
image

**Comment by mark-yacoub** [comment]
There is also this warning which is actually fun to fix. your choice of fixing it after we merge this one or as another commit on the same PR.
the warning comes because of this
node_modules/react-native-progress-bar-animated/src/AnimatedProgressBar.js

image

**Review by mark-yacoub — COMMENTED** [review]
3 comments above

**Comment by markusamuel** [comment]
Thanks @mark-yacoub. I've fixed the first error but I think it would be better to hold off on the "componentwillReceiveUpdates" for another PR

**Pull request merged**
